const mongoose = require('mongoose');

const caseSchema = new mongoose.Schema({
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    title: { type: String, required: true },
    description: { type: String, required: true },
    transcription: { type: String }, // From Whisper
    legalDraft: { type: String }, // Generated by Gemini
    status: { type: String, enum: ['open', 'in_progress', 'resolved'], default: 'open' }
}, { timestamps: true });

module.exports = mongoose.model('Case', caseSchema);
